const dessertsMenuData =
[
    {
        "super_category_ids": "6690db2413c9d3a55604693a",
        "Items": [
            {
                "_id": "6666aac208a8195cc02ca277",
                "variation": [],
                "addon": [],
                "pricing": [
                    {
                        "_id": "666ad192a9d18d81135d4a7e",
                        "area_id": "666414ee08a8195cc02c3cf8",
                        "price": 0,
                        "live": true
                    },
                    {
                        "_id": "666ad192a9d18d81135d4a7f",
                        "area_id": "666414ee08a8195cc02c3cf9",
                        "price": 0,
                        "live": true
                    }
                ],
                "Customisation": [],
                "Name": "Chocolate Muffin",
                "Price": 99,
                "AcPrice": 0,
                "gst": 5,
                "vat": 0,
                "AR": false,
                "Description": "",
                "item_image": "https://restaurantimages.s3.ap-south-1.amazonaws.com/Samvene The Bagel Cafe/ItemImages/Chocolate Muffin/1718276495028Chocolate Muffin.jpg",
                "Live": true,
                "item_type": "1",
                "serving_time": 0,
                "model_android": "url",
                "model_ios": "url",
                "Vegan": false,
                "Gluten_free": false,
                "Best_seller": false,
                "Chefs_special": false,
                "Jain": false,
                "Seasonal": false,
                "rating": 0,
                "nor": 0,
                "view_more": false,
                "drinks": false,
                "print_area": "666414ee08a8195cc02c3cf5"
            },
            {
                "_id": "6666aaca08a8195cc02ca27a",
                "variation": [],
                "addon": [],
                "pricing": [
                    {
                        "_id": "666ad166a9d18d81135d4a75",
                        "area_id": "666414ee08a8195cc02c3cf8",
                        "price": 0,
                        "live": true
                    },
                    {
                        "_id": "666ad166a9d18d81135d4a76",
                        "area_id": "666414ee08a8195cc02c3cf9",
                        "price": 0,
                        "live": true
                    }
                ],
                "Customisation": [],
                "Name": "Vanilla Muffin",
                "Price": 99,
                "AcPrice": 0,
                "gst": 5,
                "vat": 0,
                "AR": false,
                "Description": "",
                "item_image": "https://restaurantimages.s3.ap-south-1.amazonaws.com/Samvene The Bagel Cafe/ItemImages/Vanilla Muffin/1718276451375Vanilla Muffin.jpg",
                "Live": true,
                "item_type": "1",
                "serving_time": 0,
                "model_android": "url",
                "model_ios": "url",
                "Vegan": false,
                "Gluten_free": false,
                "Best_seller": false,
                "Chefs_special": false,
                "Jain": false,
                "Seasonal": false,
                "rating": 0,
                "nor": 0,
                "view_more": false,
                "drinks": false,
                "print_area": "666414ee08a8195cc02c3cf5"
            },
            {
                "_id": "6666aae008a8195cc02ca27f",
                "variation": [],
                "addon": [],
                "pricing": [
                    {
                        "_id": "6666aae008a8195cc02ca280",
                        "area_id": "666414ee08a8195cc02c3cf8",
                        "price": 0,
                        "live": true
                    },
                    {
                        "_id": "6666aae008a8195cc02ca281",
                        "area_id": "666414ee08a8195cc02c3cf9",
                        "price": 0,
                        "live": true
                    }
                ],
                "Customisation": [],
                "Name": "Chocolava",
                "Price": 119,
                "AcPrice": 0,
                "gst": 5,
                "vat": 0,
                "AR": false,
                "Description": "",
                "item_image": "url",
                "Live": true,
                "item_type": "1",
                "serving_time": 0,
                "model_android": "url",
                "model_ios": "url",
                "Vegan": false,
                "Gluten_free": false,
                "Best_seller": false,
                "Chefs_special": false,
                "Jain": false,
                "Seasonal": false,
                "rating": 0,
                "nor": 0,
                "view_more": false,
                "drinks": false,
                "print_area": "666414ee08a8195cc02c3cf5"
            },
            {
                "_id": "6666aaf608a8195cc02ca282",
                "variation": [],
                "addon": [],
                "pricing": [
                    {
                        "_id": "6666aaf608a8195cc02ca283",
                        "area_id": "666414ee08a8195cc02c3cf8",
                        "price": 0,
                        "live": true
                    },
                    {
                        "_id": "6666aaf608a8195cc02ca284",
                        "area_id": "666414ee08a8195cc02c3cf9",
                        "price": 0,
                        "live": true
                    }
                ],
                "Customisation": [],
                "Name": "Decadent Pastry",
                "Price": 179,
                "AcPrice": 0,
                "gst": 5,
                "vat": 0,
                "AR": false,
                "Description": "",
                "item_image": "url",
                "Live": true,
                "item_type": "1",
                "serving_time": 0,
                "model_android": "url",
                "model_ios": "url",
                "Vegan": false,
                "Gluten_free": false,
                "Best_seller": false,
                "Chefs_special": false,
                "Jain": false,
                "Seasonal": false,
                "rating": 0,
                "nor": 0,
                "view_more": false,
                "drinks": false,
                "print_area": "666414ee08a8195cc02c3cf5"
            },
            {
                "_id": "6666ab0608a8195cc02ca285",
                "variation": [],
                "addon": [],
                "pricing": [
                    {
                        "_id": "666ad0cea9d18d81135d4a51",
                        "area_id": "666414ee08a8195cc02c3cf8",
                        "price": 0,
                        "live": true
                    },
                    {
                        "_id": "666ad0cea9d18d81135d4a52",
                        "area_id": "666414ee08a8195cc02c3cf9",
                        "price": 0,
                        "live": true
                    }
                ],
                "Customisation": [],
                "Name": "Richie Rich Pastry",
                "Price": 199,
                "AcPrice": 0,
                "gst": 5,
                "vat": 0,
                "AR": false,
                "Description": "",
                "item_image": "https://restaurantimages.s3.ap-south-1.amazonaws.com/Samvene The Bagel Cafe/ItemImages/Richie Rich Pastry/1718276300058Richie Rich Pastry.jpg",
                "Live": true,
                "item_type": "1",
                "serving_time": 0,
                "model_android": "url",
                "model_ios": "url",
                "Vegan": false,
                "Gluten_free": false,
                "Best_seller": false,
                "Chefs_special": false,
                "Jain": false,
                "Seasonal": false,
                "rating": 0,
                "nor": 0,
                "view_more": false,
                "drinks": false,
                "print_area": "666414ee08a8195cc02c3cf5"
            },
            {
                "_id": "6666ab1408a8195cc02ca289",
                "variation": [],
                "addon": [],
                "pricing": [
                    {
                        "_id": "667d57af125ca02719ade052",
                        "area_id": "666414ee08a8195cc02c3cf8",
                        "price": 0,
                        "live": true
                    },
                    {
                        "_id": "667d57af125ca02719ade053",
                        "area_id": "666414ee08a8195cc02c3cf9",
                        "price": 0,
                        "live": true
                    }
                ],
                "Customisation": [],
                "Name": "Sizzling Brownie",
                "Price": 199,
                "AcPrice": 0,
                "gst": 5,
                "vat": 0,
                "AR": false,
                "Description": "",
                "item_image": "https://restaurantimages.s3.ap-south-1.amazonaws.com/Samvene The Bagel Cafe/ItemImages/Sizzling Brownie/17194904764831719386605984download (1).jpeg",
                "Live": true,
                "item_type": "1",
                "serving_time": 0,
                "model_android": "url",
                "model_ios": "url",
                "Vegan": false,
                "Gluten_free": false,
                "Best_seller": false,
                "Chefs_special": false,
                "Jain": false,
                "Seasonal": false,
                "rating": 0,
                "nor": 0,
                "view_more": false,
                "drinks": false,
                "print_area": "666414ee08a8195cc02c3cf5"
            },
            {
                "_id": "6666ab2d08a8195cc02ca28c",
                "variation": [],
                "addon": [],
                "pricing": [
                    {
                        "_id": "6666ab3c08a8195cc02ca290",
                        "area_id": "666414ee08a8195cc02c3cf8",
                        "price": 0,
                        "live": true
                    },
                    {
                        "_id": "6666ab3c08a8195cc02ca291",
                        "area_id": "666414ee08a8195cc02c3cf9",
                        "price": 0,
                        "live": true
                    }
                ],
                "Customisation": [],
                "Name": "Sizzling Choco lava Sundae",
                "Price": 219,
                "AcPrice": 0,
                "gst": 5,
                "vat": 0,
                "AR": false,
                "Description": "",
                "item_image": "url",
                "Live": true,
                "item_type": "1",
                "serving_time": 0,
                "model_android": "url",
                "model_ios": "url",
                "Vegan": false,
                "Gluten_free": false,
                "Best_seller": false,
                "Chefs_special": false,
                "Jain": false,
                "Seasonal": false,
                "rating": 0,
                "nor": 0,
                "view_more": false,
                "drinks": false,
                "print_area": "666414ee08a8195cc02c3cf5"
            }
        ],
        "_id": "6666aaa608a8195cc02ca276",
        "Category_name": "Desserts-Cake and Pastries",
        "Live": true,
        "recommended": false,
        "specialDiscount": false,
        "tod": 1,
        "discountPercentage": 0,
        "discountValue": 0,
        "happyOffer": false
    },
    {
        "super_category_ids": "6690db2413c9d3a55604693a",
        "Items": [
            {
                "_id": "6666ab7e08a8195cc02ca294",
                "variation": [],
                "addon": [],
                "pricing": [
                    {
                        "_id": "6666ab7e08a8195cc02ca295",
                        "area_id": "666414ee08a8195cc02c3cf8",
                        "price": 0,
                        "live": true
                    },
                    {
                        "_id": "6666ab7e08a8195cc02ca296",
                        "area_id": "666414ee08a8195cc02c3cf9",
                        "price": 0,
                        "live": true
                    }
                ],
                "Customisation": [],
                "Name": "Dark Doughnut",
                "Price": 129,
                "AcPrice": 0,
                "gst": 5,
                "vat": 0,
                "AR": false,
                "Description": "",
                "item_image": "url",
                "Live": true,
                "item_type": "1",
                "serving_time": 0,
                "model_android": "url",
                "model_ios": "url",
                "Vegan": false,
                "Gluten_free": false,
                "Best_seller": false,
                "Chefs_special": false,
                "Jain": false,
                "Seasonal": false,
                "rating": 0,
                "nor": 0,
                "view_more": false,
                "drinks": false,
                "print_area": "666414ee08a8195cc02c3cf5"
            },
            {
                "_id": "6666ab8208a8195cc02ca297",
                "variation": [],
                "addon": [],
                "pricing": [
                    {
                        "_id": "6666ab8a08a8195cc02ca29a",
                        "area_id": "666414ee08a8195cc02c3cf8",
                        "price": 0,
                        "live": true
                    },
                    {
                        "_id": "6666ab8a08a8195cc02ca29b",
                        "area_id": "666414ee08a8195cc02c3cf9",
                        "price": 0,
                        "live": true
                    }
                ],
                "Customisation": [],
                "Name": "Light Doughnut",
                "Price": 129,
                "AcPrice": 0,
                "gst": 5,
                "vat": 0,
                "AR": false,
                "Description": "",
                "item_image": "url",
                "Live": true,
                "item_type": "1",
                "serving_time": 0,
                "model_android": "url",
                "model_ios": "url",
                "Vegan": false,
                "Gluten_free": false,
                "Best_seller": false,
                "Chefs_special": false,
                "Jain": false,
                "Seasonal": false,
                "rating": 0,
                "nor": 0,
                "view_more": false,
                "drinks": false,
                "print_area": "666414ee08a8195cc02c3cf5"
            },
            {
                "_id": "6666ab9d08a8195cc02ca29d",
                "variation": [],
                "addon": [],
                "pricing": [
                    {
                        "_id": "6666ab9d08a8195cc02ca29e",
                        "area_id": "666414ee08a8195cc02c3cf8",
                        "price": 0,
                        "live": true
                    },
                    {
                        "_id": "6666ab9d08a8195cc02ca29f",
                        "area_id": "666414ee08a8195cc02c3cf9",
                        "price": 0,
                        "live": true
                    }
                ],
                "Customisation": [],
                "Name": "Mixed Berry Baked Yoghurt",
                "Price": 169,
                "AcPrice": 0,
                "gst": 5,
                "vat": 0,
                "AR": false,
                "Description": "",
                "item_image": "url",
                "Live": true,
                "item_type": "1",
                "serving_time": 0,
                "model_android": "url",
                "model_ios": "url",
                "Vegan": false,
                "Gluten_free": false,
                "Best_seller": false,
                "Chefs_special": false,
                "Jain": false,
                "Seasonal": false,
                "rating": 0,
                "nor": 0,
                "view_more": false,
                "drinks": false,
                "print_area": "666414ee08a8195cc02c3cf5"
            },
            {
                "_id": "6666aba108a8195cc02ca2a0",
                "variation": [],
                "addon": [],
                "pricing": [
                    {
                        "_id": "6666abb208a8195cc02ca2a8",
                        "area_id": "666414ee08a8195cc02c3cf8",
                        "price": 0,
                        "live": true
                    },
                    {
                        "_id": "6666abb208a8195cc02ca2a9",
                        "area_id": "666414ee08a8195cc02c3cf9",
                        "price": 0,
                        "live": true
                    }
                ],
                "Customisation": [],
                "Name": "Strawberry Baked Yoghurt",
                "Price": 169,
                "AcPrice": 0,
                "gst": 5,
                "vat": 0,
                "AR": false,
                "Description": "",
                "item_image": "url",
                "Live": true,
                "item_type": "1",
                "serving_time": 0,
                "model_android": "url",
                "model_ios": "url",
                "Vegan": false,
                "Gluten_free": false,
                "Best_seller": false,
                "Chefs_special": false,
                "Jain": false,
                "Seasonal": false,
                "rating": 0,
                "nor": 0,
                "view_more": false,
                "drinks": false,
                "print_area": "666414ee08a8195cc02c3cf5"
            },
            {
                "_id": "6666abc108a8195cc02ca36e",
                "variation": [],
                "addon": [],
                "pricing": [
                    {
                        "_id": "667d57b6125ca02719ade054",
                        "area_id": "666414ee08a8195cc02c3cf8",
                        "price": 0,
                        "live": true
                    },
                    {
                        "_id": "667d57b6125ca02719ade055",
                        "area_id": "666414ee08a8195cc02c3cf9",
                        "price": 0,
                        "live": true
                    }
                ],
                "Customisation": [],
                "Name": "Blueberry Cheesecake",
                "Price": 199,
                "AcPrice": 0,
                "gst": 5,
                "vat": 0,
                "AR": false,
                "Description": "",
                "item_image": "https://restaurantimages.s3.ap-south-1.amazonaws.com/Samvene The Bagel Cafe/ItemImages/Blueberry Cheesecake/1718275643738Cheesecake.jpg",
                "Live": true,
                "item_type": "1",
                "serving_time": 0,
                "model_android": "url",
                "model_ios": "url",
                "Vegan": false,
                "Gluten_free": false,
                "Best_seller": false,
                "Chefs_special": false,
                "Jain": false,
                "Seasonal": false,
                "rating": 0,
                "nor": 0,
                "view_more": false,
                "drinks": false,
                "print_area": "666414ee08a8195cc02c3cf5"
            },
            {
                "_id": "6666abc508a8195cc02ca371",
                "variation": [],
                "addon": [],
                "pricing": [
                    {
                        "_id": "666ace35a9d18d81135d4994",
                        "area_id": "666414ee08a8195cc02c3cf8",
                        "price": 0,
                        "live": true
                    },
                    {
                        "_id": "666ace35a9d18d81135d4995",
                        "area_id": "666414ee08a8195cc02c3cf9",
                        "price": 0,
                        "live": true
                    }
                ],
                "Customisation": [],
                "Name": "Strawberry Cheesecake",
                "Price": 199,
                "AcPrice": 0,
                "gst": 5,
                "vat": 0,
                "AR": false,
                "Description": "",
                "item_image": "https://restaurantimages.s3.ap-south-1.amazonaws.com/Samvene The Bagel Cafe/ItemImages/Strawberry Cheesecake/1718275634444Cheesecake.jpg",
                "Live": true,
                "item_type": "1",
                "serving_time": 0,
                "model_android": "url",
                "model_ios": "url",
                "Vegan": false,
                "Gluten_free": false,
                "Best_seller": false,
                "Chefs_special": false,
                "Jain": false,
                "Seasonal": false,
                "rating": 0,
                "nor": 0,
                "view_more": false,
                "drinks": false,
                "print_area": "666414ee08a8195cc02c3cf5"
            },
            {
                "_id": "6666abdc08a8195cc02ca376",
                "variation": [],
                "addon": [],
                "pricing": [
                    {
                        "_id": "6666abdc08a8195cc02ca377",
                        "area_id": "666414ee08a8195cc02c3cf8",
                        "price": 0,
                        "live": true
                    },
                    {
                        "_id": "6666abdc08a8195cc02ca378",
                        "area_id": "666414ee08a8195cc02c3cf9",
                        "price": 0,
                        "live": true
                    }
                ],
                "Customisation": [],
                "Name": "Tiramisu",
                "Price": 199,
                "AcPrice": 0,
                "gst": 5,
                "vat": 0,
                "AR": false,
                "Description": "",
                "item_image": "url",
                "Live": true,
                "item_type": "1",
                "serving_time": 0,
                "model_android": "url",
                "model_ios": "url",
                "Vegan": false,
                "Gluten_free": false,
                "Best_seller": false,
                "Chefs_special": false,
                "Jain": false,
                "Seasonal": false,
                "rating": 0,
                "nor": 0,
                "view_more": false,
                "drinks": false,
                "print_area": "666414ee08a8195cc02c3cf5"
            },
            {
                "_id": "6666abe908a8195cc02ca379",
                "variation": [],
                "addon": [],
                "pricing": [
                    {
                        "_id": "667d57ba125ca02719ade056",
                        "area_id": "666414ee08a8195cc02c3cf8",
                        "price": 0,
                        "live": true
                    },
                    {
                        "_id": "667d57ba125ca02719ade057",
                        "area_id": "666414ee08a8195cc02c3cf9",
                        "price": 0,
                        "live": true
                    }
                ],
                "Customisation": [],
                "Name": "Banoffee Pie",
                "Price": 199,
                "AcPrice": 0,
                "gst": 5,
                "vat": 0,
                "AR": false,
                "Description": "",
                "item_image": "https://restaurantimages.s3.ap-south-1.amazonaws.com/Samvene The Bagel Cafe/ItemImages/Banoffee Pie/1718275361977Banoffee Pie.jpg",
                "Live": true,
                "item_type": "1",
                "serving_time": 0,
                "model_android": "url",
                "model_ios": "url",
                "Vegan": false,
                "Gluten_free": false,
                "Best_seller": false,
                "Chefs_special": false,
                "Jain": false,
                "Seasonal": false,
                "rating": 0,
                "nor": 0,
                "view_more": false,
                "drinks": false,
                "print_area": "666414ee08a8195cc02c3cf5"
            },
            {
                "_id": "6666abf908a8195cc02ca37c",
                "variation": [],
                "addon": [],
                "pricing": [
                    {
                        "_id": "666acecaa9d18d81135d49c8",
                        "area_id": "666414ee08a8195cc02c3cf8",
                        "price": 0,
                        "live": true
                    },
                    {
                        "_id": "666acecaa9d18d81135d49c9",
                        "area_id": "666414ee08a8195cc02c3cf9",
                        "price": 0,
                        "live": true
                    }
                ],
                "Customisation": [],
                "Name": "Chocolate Mousse",
                "Price": 199,
                "AcPrice": 0,
                "gst": 5,
                "vat": 0,
                "AR": false,
                "Description": "",
                "item_image": "https://restaurantimages.s3.ap-south-1.amazonaws.com/Samvene The Bagel Cafe/ItemImages/Chocolate Mousse/1718275783230Chocolate Mousse.jpg",
                "Live": true,
                "item_type": "1",
                "serving_time": 0,
                "model_android": "url",
                "model_ios": "url",
                "Vegan": false,
                "Gluten_free": false,
                "Best_seller": false,
                "Chefs_special": false,
                "Jain": false,
                "Seasonal": false,
                "rating": 0,
                "nor": 0,
                "view_more": false,
                "drinks": false,
                "print_area": "666414ee08a8195cc02c3cf5"
            }
        ],
        "_id": "6666ab5e08a8195cc02ca292",
        "Category_name": "Desserts Specialties",
        "Live": true,
        "recommended": false,
        "specialDiscount": false,
        "tod": 1,
        "discountPercentage": 0,
        "discountValue": 0,
        "happyOffer": false
    }
];